### ISSUE TITLE
Error while running the covfefe.py file 

### ISSUE THREAD

**Issue by anandhperumal** [SPOClab-ca/COVFEFE#18]
```
anandhpe@cpu8ram30:~/installs/GitHub/COVFEFE$ python3 covfefe.py -i input_data/ -o output_data/-p lex
/home/anandhpe_ualberta_ca/.local/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.6) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "covfefe.py", line 11, in <module>
    from pipelines import pipeline_registry
  File "/home/anandhpe_ualberta_ca/installs/GitHub/COVFEFE/pipelines/__init__.py", line 11, in <module>
    importlib.import_module(_pkg_name + "." + module[:-3])
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/anandhpe_ualberta_ca/installs/GitHub/COVFEFE/pipelines/pipelines.py", line 5, in <module>
    from utils.segment_mappers import TxtSegments, EafSegments
  File "/home/anandhpe_ualberta_ca/installs/GitHub/COVFEFE/utils/segment_mappers.py", line 5, in <module>
    from utils.eaf_helper import eaf2df
  File "/home/anandhpe_ualberta_ca/installs/GitHub/COVFEFE/utils/eaf_helper.py", line 4, in <module>
    import pandas as pd
  File "/home/anandhpe_ualberta_ca/.local/lib/python3.6/site-packages/pandas/__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "/home/anandhpe_ualberta_ca/.local/lib/python3.6/site-packages/pandas/core/api.py", line 10, in <module>
    from pandas.core.groupby.groupby import Grouper
  File "/home/anandhpe_ualberta_ca/.local/lib/python3.6/site-packages/pandas/core/groupby/__init__.py", line 2, in <module>
    from pandas.core.groupby.groupby import (
  File "/home/anandhpe_ualberta_ca/.local/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 46, in <module>
    from pandas.core.index import (Index, MultiIndex,
  File "/home/anandhpe_ualberta_ca/.local/lib/python3.6/site-packages/pandas/core/index.py", line 2, in <module>
    from pandas.core.indexes.api import *
  File "/home/anandhpe_ualberta_ca/.local/lib/python3.6/site-packages/pandas/core/indexes/api.py", line 4, in <module>
    from pandas.core.indexes.base import (Index,
  File "/home/anandhpe_ualberta_ca/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 53, in <module>
    from pandas.core import ops
  File "/home/anandhpe_ualberta_ca/.local/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 23, in <module>
    from pandas.core.dtypes.common import (
ImportError: cannot import name 'ensure_object'
```

**Comment by anandhperumal** [comment]
reinstalling pandas worked
